### ISSUE TITLE
Doesn't work on v18

### ISSUE THREAD

**Issue by RkShaRkz** [Klonan/belt_buffer#1]
First off, it's incompatible with v18.

Once the stuff in info.json is bumped to 18, the first startup error is this:
![Factorio 0 18 2 6_13_2020 23_03_29](https://user-images.githubusercontent.com/7498356/84579264-b9c74780-adcc-11ea-849b-90fd3a2362de.png)

After bumping the `active_energy_usage` to 0.5J, the following error happens:
![Factorio 0 18 2 6_13_2020 23_04_53](https://user-images.githubusercontent.com/7498356/84579284-d6fc1600-adcc-11ea-8094-e3f04815b2e7.png)

adding the `icon_mipmaps = 0` doesn't resolve the issue, but it seems to work fine when the buffer-icon.png is rescaled to 64x64.

**Comment by RkShaRkz** [comment]
I'll consider making a PR that supports all 3 belt types if this ends up working and does what i think/hope it does.

**Comment by RkShaRkz** [comment]
When actually fixed to run, this is what it looks like:

![wtf](https://user-images.githubusercontent.com/7498356/84579571-0744b400-adcf-11ea-9f8d-4fd88c98bb30.png)

and does not actually let items through itself at all.
even items manually put into it can't get down the belt.

**Comment by Klonan** [comment]
Yea, I don't plan to support 0.18, sorry, you can fork the mod and try to update yourself
